site_name: Source Institute
site_url: https://source.institute/
markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - tables
theme:
  name: material
  font: false
  logo: /assets/source_logo.png
  favicon: /assets/source_logo.png
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
  plugins:
    - search
    - social:
      cards_font: Oxygen
extra:
  analytics:
      provider: custom
      property: foobar
extra_css:
  - css/source.css
